### ISSUE TITLE
Contributors page

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-website#5]
@atomrab I would like to add a Contributors page to the site that we can link to from the home page. Can you take a look at http://perio.do/contributors/ and tell me what you think and whom we're missing?

**Comment by atomrab** [comment]
@rybesh Are we including everyone who submitted a patch of any sort to the database, or are we differentiating between the grads who worked on it and the people who submitted from outside? Let me start with that.

The UT graduate students who were employed by the project after Sarah Buchanan are Jonathan Maclellan, Elijah Fleming, Stefanie Carter, and Thomas Rover.

Early external contributors include Hayes (submitted patch normally), Bocinsky (submitted patch normally), Lynam (wrote his own JSON and submitted), and Hanley, but also David Stott, Pietro Liuzzo, and Seta Stuhec, as soon as I can get the final version from her. There may also be some others -- I assume this is all part of the patch history, so whoever is there apart from the grads should be credited, unless we have a temporal cutoff (only the early adopters?). 

Dataset contributors in the next reply.

**Comment by atomrab** [comment]
@rybesh here are the folks who contributed actual datasets, but didn't submit patches themselves (bold if you already have them in the list, with links if you don't):

**Archaeology Data Service**
[ARIADNE](http://www.ariadne-infrastructure.eu/)
**British Museum**
[China Historical GIS](http://sites.fas.harvard.edu/~chgis/)
[Digital Index of North American Archaeology](http://ux.opencontext.org/archaeology-site-data/)
**Fasti Online**
[Epigraphic Database Heidelberg](https://edh-www.adw.uni-heidelberg.de/home)
[Historiska Museet, Sweden](http://historiska.se/home/) (this periodization was provided not by the museum directly, but by Marcus Smith, who I think works with it -- it's in a published document)
**Hypermedia Research Unit** (this is the indirect route by which we obtained the English Heritage periodization, so we should list them and not EH; also, I think we used the Seneschal/Heritage Data platform, http://www.heritagedata.org/blog/, so I wonder if we shouldn't link directly to that here)
[Incipit-CSIC](http://www.incipit.csic.es/en/Default.aspx)
**Levantine Ceramics Project**
[Library of Congress Linked Data Service](https://id.loc.gov/) (I think this is only fair -- Nate Trail really helped us out with the data dump, and although the material is publicly available, I used the version he passed on a lot when trying to bring it to completion, and to test the reconciliation service)
**Pleiades**
[Portable Antiquities Scheme](https://finds.org.uk/)
[Pyla-Koutsopetria Archaeological Project](http://www.pkap.org/)
[Rijksdienst voor het Cultureel Erfgoed](https://cultureelerfgoed.nl/) (this periodization was provided by Ronald Visser and its use was authorized by Arthur Sloos, but it's also in a published document)
**UCLA Encyclopedia of Egyptology**

**Comment by atomrab** [comment]
@rybesh the following contributors fall into a separate category -- they went to some trouble to provide data or have agreed to integrate PeriodO into their datasets, but for whatever reason the material they provided couldn't actually be incorporated, or we're still waiting for the collaboration to mature (ARC, Europeana, DAI -- still no data from Chronontology -- and Pelagios). I've bolded the ones in the list and added some others.

[Advanced Research Consortium](http://idhmcmain.tamu.edu/arcgrant/) (may be able to begin integration when we've managed to get some literary periods into the dataset)
**ArcheoInf** (labels but no dates)
[Athenian Agora Excavations](http://www.agathe.gr/) (we still have a chronological dump from Bruce Harzler that we should eventually mess with -- combination of labels and date-ranges derived from finds)
**CLAROS** (dates but no labels)
[Europeana](https://www.europeana.eu/portal/en) (Hugo Manguinhas passed on an export of the period labels they had after the first workshop, which we've used for reconciliation testing but haven't added to the dataset)
**German Archaeological Institute**
[Getty Research Institute](https://www.getty.edu/research/tools/vocabularies/) (we received a JSON version of the AAT from Dennis Wuthrich, but haven't had time to explore it since the reconciliation service has been refined)
[Open Context](https://opencontext.org/) (OC was the vehicle for the DINAA periods and is working with us on integration, so it seems reasonable to put it here)
[PaleoCore](http://paleocore.org/) (Denné Reed has been consulting with us on geological periods, and will integrate as soon as we get that going)
**Pelagios Commons** (better to use their current address, http://commons.pelagios.org/, since the other one just redirects anyway; they don't have any periods, but they've partially integrated ours into the [Peripleo browser](http://peripleo.pelagios.org/), so perhaps worth linking out to that)
[tDAR](https://www.tdar.org/) (still haven't parsed or integrated the material Adam Brin sent on)

**Comment by atomrab** [comment]
@rybesh I'm sure I've forgotten someone or some project, but this is at least a start. Let's not forget to add Simon Fox and/or his chronostratigraphic chart project when we manage to move ahead with that. I also wonder if we shouldn't recognize the members of our advisory board and the projects they represent, along with groups like the Timeline Consortium, the World Historical Gazetteer, or the Berkeley Prosopography Seminar, who have been open to collaboration with us even if they're not providing data, implementing PeriodO URIs, or directly contributing to our development. Also, what about the contributions of the outside developers?

**Comment by rybesh** [comment]
http://perio.do/contributors/

Please reopen this issue and add names if we're missing anyone.
